[window]
padding_x = 0
padding_y = 0
startup_mode = "Maximized"
width = 1200 # in px
height = 800 # in px

[fonts]
family = "Monaco"
size = 18
line_height = 1.2

[colors]
background = '#111111'
foreground = '#CCCCCC'
cursor = '#CCCCCC'

[bell]
enabled = false
